couch_designdoc_filtered={"_design_doc.view_index.waiting_commit",
"_design_doc.view_index.updater_running",
"_design_doc.view_index.sizes.file",
"_design_doc.view_index.sizes.active",
"_design_doc.view_index.compact_running"
}

couch_designdoc_completed={"_design_doc.view_index.updates_pending.minimum",
"_design_doc.view_index.updates_pending.preferred",
"_design_doc.view_index.updates_pending.total",
"_design_doc.view_index.waiting_commit",
"_design_doc.view_index.waiting_clients",
"_design_doc.view_index.updater_running",
"_design_doc.view_index.update_seq",
"_design_doc.view_index.sizes.file",
"_design_doc.view_index.sizes.active",
"_design_doc.view_index.purge_seq",
"_design_doc.view_index.compact_running"
}