couch_database_filtered={"_db_metric.sizes.file",
"_db_metric.sizes.active",
"_db_metric.doc_del_count",
"_db_metric.doc_count",
"_db_metric.compact_running",
}

couch_database_completed={"_db_metric.sizes.file",
"_db_metric.sizes.external",
"_db_metric.sizes.active",
"_db_metric.doc_del_count",
"_db_metric.doc_count",
"_db_metric.disk_format_version",
"_db_metric.compact_running",
"_db_metric.cluster.q",
"_db_metric.cluster.n",
"_db_metric.cluster.w",
"_db_metric.cluster.r"
}
